openapi: 3.0.0
info:
  title: API
  version: 1.0.0
  contact: {}
security: []
servers: []
paths:
  /api/employee: {}
components:
  links: {}
  callbacks: {}
  schemas:
    Employee:
      FName: string
      Lname: string
      Email: string
      Phone: string
      Gender: string
      Dept: string
      JobTitle: string
      Experience: int
      Salary: int